In [2]:
import os 

In [3]:
path_prefix = '/home/sunyf23/Work_station/PUF_Phenotype/Latency-DRAM-PUF-Dataset'    
image_path = os.path.join(path_prefix,'grayscale_images') 
image_labels = os.listdir(image_path)
image_labels

['delta', 'gamma', 'epsilon', 'beta', 'alpha']

In [4]:
image_path

'/home/sunyf23/Work_station/PUF_Phenotype/Latency-DRAM-PUF-Dataset/grayscale_images'

In [5]:
locations = os.listdir(os.path.join(image_path,image_labels[0]))
location_path = os.path.join(image_path,image_labels[0])
location_path

'/home/sunyf23/Work_station/PUF_Phenotype/Latency-DRAM-PUF-Dataset/grayscale_images/delta'

In [6]:
temperatures = os.listdir(os.path.join(location_path,locations[0]))
temperature_path = os.path.join(location_path,locations[0])
temperature_path

'/home/sunyf23/Work_station/PUF_Phenotype/Latency-DRAM-PUF-Dataset/grayscale_images/delta/b'

In [7]:
voltage_path = os.path.join(temperature_path,temperatures[0])
voltages = os.listdir(voltage_path)
voltages

['1.5', '1.3']

In [8]:
pattern_path = os.path.join(voltage_path,voltages[0])
patterns = os.listdir(pattern_path)
patterns

['pat0', 'pat1', 'patm']

In [9]:
fig_path = os.path.join(pattern_path,patterns[0])
figs = os.listdir(fig_path)
figs


['delta_b_20_1.5_pat0_grayscale_4_.png',
 'delta_b_20_1.5_pat0_grayscale_3_.png',
 'delta_b_20_1.5_pat0_grayscale_10_.png',
 'delta_b_20_1.5_pat0_grayscale_7_.png',
 'delta_b_20_1.5_pat0_grayscale_5_.png',
 'delta_b_20_1.5_pat0_grayscale_9_.png',
 'delta_b_20_1.5_pat0_grayscale_8_.png',
 'delta_b_20_1.5_pat0_grayscale_6_.png',
 'delta_b_20_1.5_pat0_grayscale_1_.png',
 'delta_b_20_1.5_pat0_grayscale_2_.png']

In [10]:
locations = os.listdir(os.path.join(image_path,image_labels[0]))
location_path = os.path.join(image_path,image_labels[0])
temperatures = os.listdir(os.path.join(location_path,locations[0]))
temperature_path = os.path.join(location_path,locations[0])
voltage_path = os.path.join(temperature_path,temperatures[0])
voltages = os.listdir(voltage_path)
pattern_path = os.path.join(voltage_path,voltages[0])
patterns = os.listdir(pattern_path)
fig_path = os.path.join(pattern_path,patterns[0])
figs = os.listdir(fig_path)

In [15]:
images = []
labels = []
dimm_locations = []
dimm_tempatures = []
dimm_voltages = []
dimm_patterns = []
for i in image_labels:
    locations = os.listdir(os.path.join(image_path,i))
    location_path = os.path.join(image_path,i)
    for j in locations:
        temperatures = os.listdir(os.path.join(location_path,j))
        temperature_path = os.path.join(location_path,j)
        for k in temperatures:
            voltage_path = os.path.join(temperature_path,k)
            voltages = os.listdir(voltage_path)
            for v in voltages:
                pattern_path = os.path.join(voltage_path,v)
                patterns = os.listdir(pattern_path)
                for p in patterns:
                    fig_path = os.path.join(pattern_path,p)
                    figs = os.listdir(fig_path)
                    for f in figs:
                        temp = os.path.join(fig_path,f)
                        if os.path.exists(temp):
                            images.append(temp)
                            labels.append(i)
                            dimm_locations.append(j)
                            dimm_tempatures.append(k)
                            dimm_voltages.append(v)
                            dimm_patterns.append(p)



                        


In [26]:
import pandas as pd
data_dict = {
    'images':images,
    'labels':labels,
    'dimm_locations':dimm_locations,
    'dimm_tempatures':dimm_tempatures,
    'dimm_voltages':dimm_voltages,
    'dimm_patterns':dimm_patterns

}
len(pd.DataFrame.from_dict(data_dict))//5


1905

In [25]:
img_df = pd.DataFrame.from_dict(data_dict)
img_df.loc[3,'labels']

'delta'

In [31]:
a=list(range(5))
a.remove(1)
a

[0, 2, 3, 4]

In [28]:
type(list(range(5))[1])

int

In [33]:
[1,2,3,4,5,6][True,True,True,True,True,True]

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_182756/2747825379.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1,2,3,4,5,6][True,True,True,True,True,True]
/tmp/ipykernel_182756/2747825379.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1,2,3,4,5,6][True,True,True,True,True,True]
/tmp/ipykernel_182756/2747825379.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1,2,3,4,5,6][True,True,True,True,True,True]


TypeError: list indices must be integers or slices, not tuple

In [34]:
from torch.utils.data import DataLoader,Subset,ConcatDataset
from dataset import PUFImageDataset
import random,torch,os
import numpy as np
import pandas as pd


seed = 1
k_fold = 5


dataset_all = PUFImageDataset(path_prefix='/home/sunyf23/Work_station/PUF_Phenotype/Latency-DRAM-PUF-Dataset')
indices = list(range(len(dataset_all)))
random.seed(seed)
random.shuffle(indices)
sub_len = len(indices)//k_fold

k_set = []
for i in range(k_fold-1):
    k_set.append(Subset(dataset=dataset_all,indices=indices[sub_len*1:sub_len*(i+1)]))
k_set.append(Subset(dataset=dataset_all,indices=indices[sub_len*(k_fold-1):]))



In [35]:
k_set

In [ ]:
for i in range(k_fold):
    train_index = list(range(k_fold))
    train_index.remove(i)
    train_dataset = ConcatDataset(k_set[j] for j in train_index)
    test_dataset = k_set[i]
    train_dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True)
    print(len(train_dataloader))
    test_dataloader = DataLoader(test_dataset, batch_size=64, shuffle=True)

In [1]:
from torchvision.io import read_image
a = read_image('/home/sunyf23/Work_station/PUF_Phenotype/Latency-DRAM-PUF-Dataset/grayscale_images/delta/b/20/1.5/pat1/delta_b_20_1.5_pat1_grayscale_1_.png')
a.size()


torch.Size([1, 220, 200])

In [3]:
import torch 
torch.concat([a,a,a]).size()


torch.Size([3, 220, 200])

In [38]:
import torch
a = torch.randint(0,2,(64,5,5))
b = torch.randint(0,2,(64,5,5))
(a.argmax(1)==b.argmax(1)).type(torch.float).sum().item()

100.0

In [40]:
a.flatten(1).size()

torch.Size([64, 25])

In [42]:
import pandas as pd
data = pd.read_csv('/home/sunyf23/Work_station/data.csv')
data['images']

0       ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
1       ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
2       ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
3       ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
4       ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
                              ...                        
3121    ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
3122    ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
3123    ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
3124    ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
3125    ['/home/sunyf23/Work_station/PUF_Phenotype/Lat...
Name: images, Length: 3126, dtype: object

In [47]:
images = data.images
for i in range(len(images)):
    path3 = images[i]
    for j in path3:
        pass


In [58]:
'/home/sunyf23/Work_station/PUF_Phenotype/Latency-DRAM-PUF-Dataset/grayscale_images/delta/b/20/1.5/patm/delta_b_20_1.5_patm_grayscale_6_.png'.split('/')[-1].split('_')

['delta', 'b', '20', '1.5', 'patm', 'grayscale', '6', '.png']

In [1]:
import torch
a = 0
b = torch.ones((3,4,5))
a+b

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [2]:
c = torch.ones_like(b)
a+b+c

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])

In [3]:
c/2

tensor([[[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]]])

In [5]:
c.to('cuda')/2


tensor([[[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]]], device='cuda:0')

In [1]:
import torch
a= torch.LongTensor([[1,2,3,4,5,6],[1,9,3,4,5,6]])
a

tensor([[1, 2, 3, 4, 5, 6],
        [1, 9, 3, 4, 5, 6]])

In [5]:
import pandas as pd
a = torch.randint(low=0,high=5,size=(3000,5))
b=a.numpy()


In [6]:
b

array([[3, 1, 1, 2, 3],
       [1, 0, 4, 0, 1],
       [1, 0, 1, 4, 0],
       ...,
       [2, 0, 1, 1, 1],
       [4, 2, 1, 0, 0],
       [3, 2, 3, 3, 0]])

In [10]:
df = pd.DataFrame(b)
df.columns = ['delta', 'gamma', 'epsilon', 'beta', 'alpha']
df[df['delta']==1]

delta  gamma  epsilon  beta  alpha
1         1      0        4     0      1
2         1      0        1     4      0
5         1      1        1     0      0
9         1      0        2     1      3
25        1      4        2     3      1
...     ...    ...      ...   ...    ...
2963      1      3        2     4      4
2975      1      3        4     4      2
2978      1      1        1     0      4
2979      1      0        2     2      2
2980      1      4        3     0      4

[552 rows x 5 columns]

In [10]:
a.argmax(dim=1)

tensor([5, 1])

In [12]:
a[1]

tensor([1, 9, 3, 4, 5, 6])